scrapy:
    build: . 
    volumes:
        - ./codes:/usr/local/code
        - ./logs:/data/logs

    links:
        - "mongo"
    environment:
        - PROXY_POOL_ENV=product
    ports:
        - "5000:5000"
    tty: true

mongo:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
        - ./data/configdb:/data/configdb
        - ./data/db:/data/db
